config/routes.rb
Bane::Application.routes.draw do

  resources :test_cases

  get "pages/home"
  match "/process_input" => "pages#process_input"
  match "/history" => "pages#history"
  match "/mark" => "pages#mark_citation"
  match "/show/:id" => "pages#show", :as => :citation_history
  match "/status" => "pages#status"

  root :to => "pages#home"

end

app/models/citation_history.rb
class CitationHistory < ActiveRecord::Base
end

app/models/common_abbreviation.rb
class CommonAbbreviation < ActiveRecord::Base

    validates_uniqueness_of :word, :case_sensitive => false

end

app/models/test_case.rb
class TestCase < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def status
    @errors = Array.new
    @correct = Array.new
    TestCase.all.each do |t|
      if t.output.squish == process_input_method(t.input)["output"].squish
        @correct << [t, process_input_method(t.input)]
      else
        @errors << [t, process_input_method(t.input)]
      end
    end
  end

  def show
    @history = CitationHistory.find(params[:id])
  end

  def process_input
  	unless params[:input].blank?
      results = process_input_method(params[:input])
      @output = results["output"]
      @petitioner = results["petitioner"]
      @respondent = results["respondent"]
      @decision_year = results["decision_year"]
      @reporter_number = results["reporter_number"]
      @input = results["input"]

      @history = CitationHistory.create(:input => @input, :output => @output)
      if @output == "Error occurred!"
        @history.update_attribute(:correct, false)
      end
    end
  end

  def history
    @citation_histories = CitationHistory.find(:all, :order => 'created_at DESC')
  end

  def mark_citation
    return if (params[:v].blank? || params[:id].blank?)
    value = params[:v]
    CitationHistory.find(params[:id]).update_attribute(:correct, value)
    render :nothing => true
  end

  private

  def abbreviate_words(input = nil)
      return false if input.nil?
      result = String.new
      input.scan(/[A-Z]{2,}/) do |word|
          ca = CommonAbbreviation.find_by_word(word.downcase)
          if ca.blank?
              result = input if result.blank?
          else
              result = input.downcase.gsub!(word.downcase, ca.abbreviation)
          end
      end
      return result
  end

  def process_input_method(input=nil)
    unless input.blank?
      results = Hash.new
      results["input"] = input
      lines = Array.new
      count = 1
      input.lines.each do |l|
        lines << l
      end

      results["decision_year"] = input.scan(/\d{4}/).last
      results["reporter_number"] = lines[0] rescue 'Error occurred.'

      while (results["petitioner"].blank? && count < lines.length)
        petitioner = lines[count] rescue 'Error occurred.'
        petitioner_string = petitioner.scan(/[A-Z]{2,}\W?/)
        results["petitioner"] = abbreviate_words(petitioner_string.join(" ")).titleize
        unless (results["petitioner"].split.last.downcase.strip=="inc." rescue true)
          petitioner_dirty = results["petitioner"].split
          petitioner_dirty[petitioner_dirty.length-1] = petitioner_dirty.last.to_s.gsub(/[,|.]/, "")
          results["petitioner"] = petitioner_dirty.join(" ").titleize
        end
        count += 1
      end

      while (results["respondent"].blank? && count < lines.length)
        respondent = lines[count] rescue 'Error occurred.'
        respondent_string = respondent.scan(/[A-Z]{2,}\W?/)
        results["respondent"] = abbreviate_words(respondent_string.join(" ")).titleize
        unless (results["respondent"].split.last.downcase.strip=="inc." rescue true)
          respondent_dirty = results["respondent"].split
          respondent_dirty[respondent_dirty.length-1] = respondent_dirty.last.to_s.gsub(/[,|.]/, "")
          results["respondent"] = respondent_dirty.join(" ").titleize
        end
        count += 1
      end

      results["output"] = results['petitioner'].strip.titleize + ' v. ' + results['respondent'].strip.titleize + ", " + results['reporter_number'] + " (#{results['decision_year']})." rescue "Error occurred!"
      return results
    end
    return false
  end

end

app/controllers/test_cases_controller.rb
class TestCasesController < ApplicationController
  # GET /test_cases
  # GET /test_cases.json
  def index
    @test_cases = TestCase.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @test_cases }
    end
  end

  # GET /test_cases/1
  # GET /test_cases/1.json
  def show
    @test_case = TestCase.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @test_case }
    end
  end

  # GET /test_cases/new
  # GET /test_cases/new.json
  def new
    @test_case = TestCase.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @test_case }
    end
  end

  # GET /test_cases/1/edit
  def edit
    @test_case = TestCase.find(params[:id])
  end

  # POST /test_cases
  # POST /test_cases.json
  def create
    @test_case = TestCase.new(params[:test_case])

    respond_to do |format|
      if @test_case.save
        format.html { redirect_to @test_case, notice: 'Test case was successfully created.' }
        format.json { render json: @test_case, status: :created, location: @test_case }
      else
        format.html { render action: "new" }
        format.json { render json: @test_case.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /test_cases/1
  # PUT /test_cases/1.json
  def update
    @test_case = TestCase.find(params[:id])

    respond_to do |format|
      if @test_case.update_attributes(params[:test_case])
        format.html { redirect_to @test_case, notice: 'Test case was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @test_case.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_cases/1
  # DELETE /test_cases/1.json
  def destroy
    @test_case = TestCase.find(params[:id])
    @test_case.destroy

    respond_to do |format|
      format.html { redirect_to test_cases_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/test_cases_helper.rb
module TestCasesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />

  <title>Bane</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>

  <%= csrf_meta_tags %>
  <%= javascript_include_tag "application" %>

</head>
<body>

  <!-- Navigation -->

  <nav class="top-bar fixed">
    <ul>
      <li class="name"><h1><%= link_to "Bane", root_path %></h1></li>
    </ul>
  </nav><br><br>

  <!-- End Navigation -->


  <!-- Header -->

<div class="row">
  <div class="twelve columns centered">
    <img src="http://placehold.it/960x300&text=Header"><br><br>
  </div>
</div>

  <!-- End Header -->

  <%= yield %>

  <!-- Footer -->

  <footer class="row">
  <div class="twelve columns"><hr />
      <div class="row">

        <div class="six columns">
            <p>&copy; <%= Time.now.year %> Bane.  All rights reserved.</p>
        </div>

        <div class="six columns">
            <ul class="link-list right">
              <li><a href="#">Link 1</a></li>
              <li><a href="#">Link 2</a></li>
              <li><a href="#">Link 3</a></li>
              <li><a href="#">Link 4</a></li>
            </ul>
        </div>

      </div>
  </div>
  </footer>

</body>
</html>

app/views/pages/history.html.erb
<div class="row">
    <div class="twelve panel columns centered">
        <h3>Pages#history (should be ADMIN only!)</h3>
        <p>
            <b>
                <%= link_to "Go back to home page", root_path %>
            </b>
        </p>
        <table>
            <thead>
                <tr>
                    <th>Status</th>
                    <th>Input</th>
                    <th>Output</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
            <% @citation_histories.each do |ch| %>
             <tr>
                <td>
                    <%= ch.correct ? "<span class='round success label'>Correct</span>".html_safe : "<span class='round alert label'>Incorrect</span>".html_safe %>
                </td>
                <td>
                    <%= simple_format(ch.input) %>
                </td>
                <td>
                    <%= simple_format(ch.output) %>
                </td>
                <td><%= time_ago_in_words(ch.created_at) %> ago, <%= ch.created_at.strftime("%l:%M:%S %P, %b %e %Y") %>
                </td>
              </tr>
            <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/pages/home.html.erb
<div class="row">
	<div class="nine panel columns centered">
		<h3>Pages#home</h3>
		<p>
			<%= form_tag "/process_input", :multipart => true do %>
				<%= text_area_tag "input", nil, :placeholder => "Paste your input here", :rows => 8 %>
				<%= submit_tag "Submit", :class => "button" %>
			<% end %>
		</p>
	</div>
</div>

app/views/pages/process_input.html.erb
<style>
	span.label {
		cursor:pointer;
	}
	span.label.disabled{
		background-color: #ccc;
	}
	span.label a {
		color:white;
	}
</style>

<div class="row">
	<div class="nine panel columns centered">
		<h3>Pages#process_input</h3>
		<p>
			<b><%= link_to "Start over", root_path %></b>
			<br />
			<b>This citation is:</b>
			<span class="round success label" id="correct-citation"><%= link_to "Correct", "/mark?id=#{@history.id}&v=true", :remote => true %></span>
			<span class="round alert label" id="incorrect-citation"><%= link_to "Incorrect", "/mark?id=#{@history.id}&v=false", :remote => true %></span>
			<script>
				$('#correct-citation').click(function(){
					$('#incorrect-citation').addClass("disabled");
					$('#correct-citation').removeClass("disabled");
				});
				$('#incorrect-citation').click(function(){
					$('#correct-citation').addClass("disabled");
					$('#incorrect-citation').removeClass("disabled");
				});
			</script>
		</p>
		<table>
			<tr style="background:#D5E9FC;">
				<td>
					Output
				</td>
				<td style="font-size:18px;line-height:1.0;" id="output">
					<%=h @output %>
				</td>
			</tr>
			<tr>
				<td>
					Input stats
				</td>
				<td>
					<p>
						<%= pluralize(@input.lines.count, "line") rescue "Error occurred!" %>
						<br />
						<b>Reporter number:</b> <%= @reporter_number %>
						<br />
						<b>Petitioner:</b> <%= @petitioner %>
						<br />
						<b>Respondent:</b> <%= @respondent %>
						<br />
						<b>Decision year:</b> <%= @decision_year %>
						<br />
					</p>
				</td>
			</tr>
			<tr>
				<td>
					Input text
				</td>
				<td id="input">
					<%= simple_format(@input) %>
				</td>
			</tr>
		</table>
	</div>
</div>

app/views/pages/show.html.erb
<style>
    span.label.disabled{
        background-color: #ccc;
    }
    span.label a {
        color:white;
    }
</style>

<div class="row">
    <div class="nine panel columns centered">
        <h3>Pages#process_input</h3>
        <p>
            <b><%= link_to "Start over", root_path %></b>
            <br />
            <b>This citation is:</b>
            <span class="round <%= @history.correct ? "success" : "alert" %> label"><%= @history.correct ? "correct" : "incorrect" %></span>
        </p>
        <table>
            <tr style="background:#D5E9FC;">
                <td>
                    Output
                </td>
                <td style="font-size:18px;line-height:1.0;">
                    <%= @history.output %>
                </td>
            </tr>
            <tr>
                <td>
                    Input text
                </td>
                <td>
                    <%= simple_format(@history.input) %>
                </td>
            </tr>
        </table>
    </div>
</div>

app/views/pages/status.html.erb
<style>
    span.label {
        cursor:pointer;
    }
    span.label.disabled{
        background-color: #ccc;
    }
    span.label a {
        color:white;
    }
</style>

<div class="row">
    <div class="nine panel columns centered">
        <h3>Pages#process_input</h3>
        <p>
            <b><%= link_to "Back to home page", root_path %></b> | <b><%= link_to "Create new test case", new_test_case_path %></b>
            <br /><br />
            <b>Status: </b>
            <span class="round label <%= @errors.empty? ? 'success' : 'alert' %>">
                <%= @errors.count %> failing, <%= @correct.count %> successful, <%= @correct.count + @errors.count %> total
            </span>
            <span style="margin-left:15px;font-size:1.1em;" class="round label secondary">
                <b><%= (100*(@correct.count).abs/(@errors.count+@correct.count).to_f).round(2) %>% success rate</b>
            </span>
        </p>
        <table>
            <% @errors.each do |e| %>
                <tr style="background:#D5E9FC;">
                    <td>
                        Output
                    </td>
                    <td style="font-size:18px;line-height:1.0;" id="output">
                        <%= e[1]["output"] %>
                    </td>
                </tr>
                <tr>
                    <td>
                        Expected output
                    </td>
                    <td style="font-size:18px;line-height:1.0;" id="output">
                        <%= e[0].output %>
                    </td>
                </tr>
                <tr>
                    <td>
                        <span class="round alert label" class="incorrect-citation">Incorrect</span>
                        <br /><br />
                        <b>Test case <%= e[0].id %></b>
                    </td>
                    <td>
                        <p>
                            <%= pluralize(e[1]["input"].lines.count, "line") rescue "Error occurred!" %>
                            <br />
                            <b>Reporter number:</b> <%= e[1]["reporter_number"] %>
                            <br />
                            <b>Petitioner:</b> <%= e[1]["petitioner"] %>
                            <br />
                            <b>Respondent:</b> <%= e[1]["respondent"] %>
                            <br />
                            <b>Decision year:</b> <%= e[1]["decision_year"] %>
                            <br />
                        </p>
                    </td>
                </tr>
                <tr>
                    <td>
                        Input text
                    </td>
                    <td id="input">
                        <%= simple_format(e[1]["input"]) %>
                    </td>
                </tr>
            <% end %>
            <% @correct.each do |e| %>
                <tr style="background:#D5E9FC;">
                    <td>
                        Output
                    </td>
                    <td style="font-size:18px;line-height:1.0;" id="output">
                        <%= e[1]["output"] %>
                    </td>
                </tr>
                <tr>
                    <td>
                        Expected output
                    </td>
                    <td style="font-size:18px;line-height:1.0;" id="output">
                        <%= e[0].output %>
                    </td>
                </tr>
                <tr>
                    <td>
                        <span class="round success label" class="correct-citation">Correct</span>
                        <br /><br />
                        <b>Test case <%= e[0].id %></b>
                    </td>
                    <td>
                        <p>
                            <%= pluralize(e[1]["input"].lines.count, "line") rescue "Error occurred!" %>
                            <br />
                            <b>Reporter number:</b> <%= e[1]["reporter_number"] %>
                            <br />
                            <b>Petitioner:</b> <%= e[1]["petitioner"] %>
                            <br />
                            <b>Respondent:</b> <%= e[1]["respondent"] %>
                            <br />
                            <b>Decision year:</b> <%= e[1]["decision_year"] %>
                            <br />
                        </p>
                    </td>
                </tr>
                <tr>
                    <td>
                        Input text
                    </td>
                    <td id="input">
                        <%= simple_format(e[1]["input"]) %>
                    </td>
                </tr>
            <% end %>
        </table>
    </div>
</div>

app/views/test_cases/_form.html.erb
<%= form_for(@test_case) do |f| %>
  <% if @test_case.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_case.errors.count, "error") %> prohibited this test_case from being saved:</h2>

      <ul>
      <% @test_case.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :input %><br />
    <%= f.text_area :input %>
  </div>
  <div class="field">
    <%= f.label :output, "Expected output" %><br />
    <%= f.text_area :output %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_cases/edit.html.erb
<div class="row">
    <div class="nine panel columns centered">
        <h1>Editing test_case</h1>

        <%= render 'form' %>

        <%= link_to 'Show', @test_case %> |
        <%= link_to 'Back', test_cases_path %>
    </div>
</div>

app/views/test_cases/index.html.erb
<div class="row">
    <div class="twelve panel columns centered">
      <h1>Listing test_cases</h1>

      <%= link_to 'New Test case', new_test_case_path %>
      <br /><br />

      <table>
        <thead>
        <tr>
          <th>Input</th>
          <th>Expected output</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
          <% @test_cases.each do |test_case| %>
            <tr>
              <td><%= test_case.input %></td>
              <td><%= test_case.output %></td>
              <td><%= link_to 'Show', test_case %></td>
              <td><%= link_to 'Edit', edit_test_case_path(test_case) %></td>
              <td><%= link_to 'Destroy', test_case, confirm: 'Are you sure?', method: :delete %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br />
    </div>
</div>

app/views/test_cases/new.html.erb
<div class="row">
    <div class="nine panel columns centered">
        <h1>New test_case</h1>

        <%= render 'form' %>

        <%= link_to 'Back', test_cases_path %>
    </div>
</div>

app/views/test_cases/show.html.erb
<div class="row">
    <div class="nine panel columns centered">
        <p id="notice"><%= notice %></p>
        <p><b><%= link_to "Go to status page", status_path %></b></p>
        <p>
          <b>Input:</b>
          <%= @test_case.input %>
        </p>

        <p>
          <b>Output:</b>
          <%= @test_case.output %>
        </p>


        <%= link_to 'Edit', edit_test_case_path(@test_case) %> |
        <%= link_to 'Back', test_cases_path %>
    </div>
</div>